### PR TITLE
Safety

### LINKED ISSUE #79: Safety Measure:  Cannot press buttons or do shit if house layout file is not yet loaded

### PR DESCRIPTION
**Pull request by adrientremblay**
Revamp the ON/OFF button to instead disable controls on the front-end.  Also the simulation now starts OFF, and the House Layout must be successfully loaded in order for the simulation to first turn on.

closes #79

### CODE REVIEW

**Review by DGovi — APPROVED** [review]
I think we should still be allowed to touch the on/off button on the simulation, very minor, but other than that, everything looks good to me!

**Comment by adrientremblay** [comment]
> I think we should still be allowed to touch the on/off button on the simulation, very minor, but other than that, everything looks good to me!

what do you mean by this @DGovi ?  Im confused  :0

**Comment by DGovi** [comment]
> > I think we should still be allowed to touch the on/off button on the simulation, very minor, but other than that, everything looks good to me!
> 
> what do you mean by this @DGovi ? Im confused :0

Like when there is no house input, you should still be able to turn the simulation on/off

**Comment by adrientremblay** [comment]
> > > I think we should still be allowed to touch the on/off button on the simulation, very minor, but other than that, everything looks good to me!
> > 
> > 
> > what do you mean by this @DGovi ? Im confused :0
> 
> Like when there is no house input, you should still be able to turn the simulation on/off

sry for the late response.  I don't think so.  As if there is no house layout, what are we simulating?  haha.  Turning the simulation on, but having all the butttons disabled would be misleading I feel.  Having it start out off at the beginning is more accurate imo.   idk.

**Comment by DGovi** [comment]
coolio no problem

**Pull request merged**
